# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mathUi.ui'
#
# Created: Mon Dec 19 08:25:25 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(780, 568)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1200, 1300))
        Form.setAcceptDrops(True)
        Form.setStyleSheet("#gBtop1 QLabel{\n"
"    \n"
"font: 28pt \"FreeSans\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#gBtop2 QLabel{\n"
"font: 28pt \"FreeSans\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#gBtop3 QLabel{\n"
"font: 28pt \"FreeSans\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"#gBbot QLabel{\n"
"font: 28pt \"FreeSans\";\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.gBtop1 = QtGui.QGroupBox(Form)
        self.gBtop1.setGeometry(QtCore.QRect(10, 50, 243, 234))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBtop1.sizePolicy().hasHeightForWidth())
        self.gBtop1.setSizePolicy(sizePolicy)
        self.gBtop1.setAutoFillBackground(False)
        self.gBtop1.setStyleSheet("None")
        self.gBtop1.setTitle("")
        self.gBtop1.setObjectName("gBtop1")
        self.gridLayout_2 = QtGui.QGridLayout(self.gBtop1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label11 = QtGui.QLabel(self.gBtop1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label11.sizePolicy().hasHeightForWidth())
        self.label11.setSizePolicy(sizePolicy)
        self.label11.setText("")
        self.label11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label11.setObjectName("label11")
        self.horizontalLayout_2.addWidget(self.label11)
        self.operator1 = QtGui.QLabel(self.gBtop1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operator1.sizePolicy().hasHeightForWidth())
        self.operator1.setSizePolicy(sizePolicy)
        self.operator1.setText("")
        self.operator1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.operator1.setObjectName("operator1")
        self.horizontalLayout_2.addWidget(self.operator1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label12 = QtGui.QLabel(self.gBtop1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label12.sizePolicy().hasHeightForWidth())
        self.label12.setSizePolicy(sizePolicy)
        self.label12.setText("")
        self.label12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label12.setObjectName("label12")
        self.horizontalLayout_3.addWidget(self.label12)
        spacerItem = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line1 = QtGui.QLabel(self.gBtop1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line1.sizePolicy().hasHeightForWidth())
        self.line1.setSizePolicy(sizePolicy)
        self.line1.setText("")
        self.line1.setPixmap(QtGui.QPixmap("images/line.png"))
        self.line1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line1.setObjectName("line1")
        self.horizontalLayout_4.addWidget(self.line1)
        spacerItem1 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labela1 = QtGui.QLabel(self.gBtop1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labela1.sizePolicy().hasHeightForWidth())
        self.labela1.setSizePolicy(sizePolicy)
        self.labela1.setText("")
        self.labela1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labela1.setObjectName("labela1")
        self.horizontalLayout_5.addWidget(self.labela1)
        spacerItem2 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gBtop2 = QtGui.QGroupBox(Form)
        self.gBtop2.setGeometry(QtCore.QRect(260, 50, 242, 234))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBtop2.sizePolicy().hasHeightForWidth())
        self.gBtop2.setSizePolicy(sizePolicy)
        self.gBtop2.setStyleSheet("None")
        self.gBtop2.setTitle("")
        self.gBtop2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.gBtop2.setFlat(True)
        self.gBtop2.setObjectName("gBtop2")
        self.gridLayout_3 = QtGui.QGridLayout(self.gBtop2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label21 = QtGui.QLabel(self.gBtop2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label21.sizePolicy().hasHeightForWidth())
        self.label21.setSizePolicy(sizePolicy)
        self.label21.setText("")
        self.label21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label21.setObjectName("label21")
        self.horizontalLayout_10.addWidget(self.label21)
        self.operator2 = QtGui.QLabel(self.gBtop2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operator2.sizePolicy().hasHeightForWidth())
        self.operator2.setSizePolicy(sizePolicy)
        self.operator2.setText("")
        self.operator2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.operator2.setObjectName("operator2")
        self.horizontalLayout_10.addWidget(self.operator2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label22 = QtGui.QLabel(self.gBtop2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label22.sizePolicy().hasHeightForWidth())
        self.label22.setSizePolicy(sizePolicy)
        self.label22.setText("")
        self.label22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label22.setObjectName("label22")
        self.horizontalLayout_11.addWidget(self.label22)
        spacerItem3 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.line2 = QtGui.QLabel(self.gBtop2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line2.sizePolicy().hasHeightForWidth())
        self.line2.setSizePolicy(sizePolicy)
        self.line2.setText("")
        self.line2.setPixmap(QtGui.QPixmap("images/line.png"))
        self.line2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line2.setObjectName("line2")
        self.horizontalLayout_12.addWidget(self.line2)
        spacerItem4 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.labela2 = QtGui.QLabel(self.gBtop2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labela2.sizePolicy().hasHeightForWidth())
        self.labela2.setSizePolicy(sizePolicy)
        self.labela2.setText("")
        self.labela2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labela2.setObjectName("labela2")
        self.horizontalLayout_13.addWidget(self.labela2)
        spacerItem5 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gBtop3 = QtGui.QGroupBox(Form)
        self.gBtop3.setEnabled(True)
        self.gBtop3.setGeometry(QtCore.QRect(510, 50, 242, 234))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBtop3.sizePolicy().hasHeightForWidth())
        self.gBtop3.setSizePolicy(sizePolicy)
        self.gBtop3.setStyleSheet("None")
        self.gBtop3.setTitle("")
        self.gBtop3.setObjectName("gBtop3")
        self.gridLayout_4 = QtGui.QGridLayout(self.gBtop3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label31 = QtGui.QLabel(self.gBtop3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label31.sizePolicy().hasHeightForWidth())
        self.label31.setSizePolicy(sizePolicy)
        self.label31.setText("")
        self.label31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label31.setObjectName("label31")
        self.horizontalLayout_14.addWidget(self.label31)
        self.operator3 = QtGui.QLabel(self.gBtop3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operator3.sizePolicy().hasHeightForWidth())
        self.operator3.setSizePolicy(sizePolicy)
        self.operator3.setText("")
        self.operator3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.operator3.setObjectName("operator3")
        self.horizontalLayout_14.addWidget(self.operator3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label32 = QtGui.QLabel(self.gBtop3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label32.sizePolicy().hasHeightForWidth())
        self.label32.setSizePolicy(sizePolicy)
        self.label32.setText("")
        self.label32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label32.setObjectName("label32")
        self.horizontalLayout_15.addWidget(self.label32)
        spacerItem6 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.line3 = QtGui.QLabel(self.gBtop3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line3.sizePolicy().hasHeightForWidth())
        self.line3.setSizePolicy(sizePolicy)
        self.line3.setText("")
        self.line3.setPixmap(QtGui.QPixmap("images/line.png"))
        self.line3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line3.setObjectName("line3")
        self.horizontalLayout_16.addWidget(self.line3)
        spacerItem7 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labela3 = QtGui.QLabel(self.gBtop3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labela3.sizePolicy().hasHeightForWidth())
        self.labela3.setSizePolicy(sizePolicy)
        self.labela3.setText("")
        self.labela3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labela3.setObjectName("labela3")
        self.horizontalLayout_17.addWidget(self.labela3)
        spacerItem8 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.gBbot = QtGui.QGroupBox(Form)
        self.gBbot.setGeometry(QtCore.QRect(10, 293, 741, 231))
        self.gBbot.setStyleSheet("color: rgb(255, 255, 255);")
        self.gBbot.setTitle("")
        self.gBbot.setObjectName("gBbot")
        self.layoutWidget = QtGui.QWidget(self.gBbot)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 721, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.blabel0 = QtGui.QLabel(self.layoutWidget)
        self.blabel0.setText("")
        self.blabel0.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel0.setObjectName("blabel0")
        self.horizontalLayout.addWidget(self.blabel0)
        self.blabel1 = QtGui.QLabel(self.layoutWidget)
        self.blabel1.setText("")
        self.blabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel1.setObjectName("blabel1")
        self.horizontalLayout.addWidget(self.blabel1)
        self.blabel2 = QtGui.QLabel(self.layoutWidget)
        self.blabel2.setText("")
        self.blabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel2.setObjectName("blabel2")
        self.horizontalLayout.addWidget(self.blabel2)
        self.blabel3 = QtGui.QLabel(self.layoutWidget)
        self.blabel3.setText("")
        self.blabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel3.setObjectName("blabel3")
        self.horizontalLayout.addWidget(self.blabel3)
        self.blabel4 = QtGui.QLabel(self.layoutWidget)
        self.blabel4.setText("")
        self.blabel4.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel4.setObjectName("blabel4")
        self.horizontalLayout.addWidget(self.blabel4)
        self.blabel5 = QtGui.QLabel(self.layoutWidget)
        self.blabel5.setText("")
        self.blabel5.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel5.setObjectName("blabel5")
        self.horizontalLayout.addWidget(self.blabel5)
        self.blabel6 = QtGui.QLabel(self.layoutWidget)
        self.blabel6.setText("")
        self.blabel6.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel6.setObjectName("blabel6")
        self.horizontalLayout.addWidget(self.blabel6)
        self.blabel7 = QtGui.QLabel(self.layoutWidget)
        self.blabel7.setText("")
        self.blabel7.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel7.setObjectName("blabel7")
        self.horizontalLayout.addWidget(self.blabel7)
        self.blabel8 = QtGui.QLabel(self.layoutWidget)
        self.blabel8.setText("")
        self.blabel8.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel8.setObjectName("blabel8")
        self.horizontalLayout.addWidget(self.blabel8)
        self.blabel9 = QtGui.QLabel(self.layoutWidget)
        self.blabel9.setText("")
        self.blabel9.setAlignment(QtCore.Qt.AlignCenter)
        self.blabel9.setObjectName("blabel9")
        self.horizontalLayout.addWidget(self.blabel9)
        self.showButton = QtGui.QPushButton(Form)
        self.showButton.setGeometry(QtCore.QRect(740, -10, 41, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showButton.sizePolicy().hasHeightForWidth())
        self.showButton.setSizePolicy(sizePolicy)
        self.showButton.setCheckable(True)
        self.showButton.setChecked(True)
        self.showButton.setObjectName("showButton")
        self.toolsgB = QtGui.QGroupBox(Form)
        self.toolsgB.setGeometry(QtCore.QRect(10, -20, 641, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolsgB.sizePolicy().hasHeightForWidth())
        self.toolsgB.setSizePolicy(sizePolicy)
        self.toolsgB.setMinimumSize(QtCore.QSize(0, 0))
        self.toolsgB.setTitle("")
        self.toolsgB.setObjectName("toolsgB")
        self.gridLayout = QtGui.QGridLayout(self.toolsgB)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtGui.QLabel(self.toolsgB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        self.vspinBox1 = QtGui.QSpinBox(self.toolsgB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vspinBox1.sizePolicy().hasHeightForWidth())
        self.vspinBox1.setSizePolicy(sizePolicy)
        self.vspinBox1.setObjectName("vspinBox1")
        self.horizontalLayout_18.addWidget(self.vspinBox1)
        self.label_2 = QtGui.QLabel(self.toolsgB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_18.addWidget(self.label_2)
        self.vspinBox2 = QtGui.QSpinBox(self.toolsgB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vspinBox2.sizePolicy().hasHeightForWidth())
        self.vspinBox2.setSizePolicy(sizePolicy)
        self.vspinBox2.setObjectName("vspinBox2")
        self.horizontalLayout_18.addWidget(self.vspinBox2)
        self.label_3 = QtGui.QLabel(self.toolsgB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_18.addWidget(self.label_3)
        self.operatorCombo = QtGui.QComboBox(self.toolsgB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operatorCombo.sizePolicy().hasHeightForWidth())
        self.operatorCombo.setSizePolicy(sizePolicy)
        self.operatorCombo.setObjectName("operatorCombo")
        self.operatorCombo.addItem("")
        self.operatorCombo.addItem("")
        self.horizontalLayout_18.addWidget(self.operatorCombo)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem9)
        self.previouslButton = QtGui.QPushButton(self.toolsgB)
        self.previouslButton.setAutoFillBackground(False)
        self.previouslButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previouslButton.setIcon(icon)
        self.previouslButton.setObjectName("previouslButton")
        self.horizontalLayout_18.addWidget(self.previouslButton)
        self.levelLabel = QtGui.QLabel(self.toolsgB)
        self.levelLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.levelLabel.setObjectName("levelLabel")
        self.horizontalLayout_18.addWidget(self.levelLabel)
        self.nextlButton = QtGui.QPushButton(self.toolsgB)
        self.nextlButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextlButton.setIcon(icon1)
        self.nextlButton.setObjectName("nextlButton")
        self.horizontalLayout_18.addWidget(self.nextlButton)
        self.gridLayout.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.operatorCombo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.showButton.setText(QtGui.QApplication.translate("Form", "show", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "value1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "value2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "operator", None, QtGui.QApplication.UnicodeUTF8))
        self.operatorCombo.setItemText(0, QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.operatorCombo.setItemText(1, QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.levelLabel.setText(QtGui.QApplication.translate("Form", "Level 1", None, QtGui.QApplication.UnicodeUTF8))

